Return-Path: <linux1394-devel-bounces@lists.sourceforge.net>
X-Original-To: lists+linux1394-devel@lfdr.de
Delivered-To: lists+linux1394-devel@lfdr.de
Received: from lists.sourceforge.net (lists.sourceforge.net [216.105.38.7])
	by mail.lfdr.de (Postfix) with ESMTPS id 069DF4F7590
	for <lists+linux1394-devel@lfdr.de>; Thu,  7 Apr 2022 08:02:30 +0200 (CEST)
Received: from [127.0.0.1] (helo=sfs-ml-4.v29.lw.sourceforge.com)
	by sfs-ml-4.v29.lw.sourceforge.com with esmtp (Exim 4.94.2)
	(envelope-from <linux1394-devel-bounces@lists.sourceforge.net>)
	id 1ncLDo-00028P-Ol; Thu, 07 Apr 2022 06:02:19 +0000
Received: from [172.30.20.202] (helo=mx.sourceforge.net)
 by sfs-ml-4.v29.lw.sourceforge.com with esmtps (TLS1.2) tls
 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (Exim 4.94.2)
 (envelope-from <tiwai@suse.de>) id 1ncLDn-00028J-UN
 for linux1394-devel@lists.sourceforge.net; Thu, 07 Apr 2022 06:02:18 +0000
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
 d=sourceforge.net; s=x; h=Content-Type:MIME-Version:References:In-Reply-To:
 Subject:Cc:To:From:Message-ID:Date:Sender:Reply-To:Content-Transfer-Encoding:
 Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:
 Resent-To:Resent-Cc:Resent-Message-ID:List-Id:List-Help:List-Unsubscribe:
 List-Subscribe:List-Post:List-Owner:List-Archive;
 bh=zcVA2leKEHZCBy0L6O+DAKg05GvJhbtAx6yj2EYofvk=; b=k31YWu0P5pX1c9GJQlde43CS9O
 gJPnd4zTzDAJoDrbvc2BUgPvkuLjYj9us0K+n3wqUV2m+b5+l1FrV2b+90ifMcz2BbVbEMkC6I6l/
 7a9kRReotfIb5WOJaJZ7bdxBtuy4i3v2Ro8+pAEaFknXtAXmFvJdjMJt3uc3QDtcHeYY=;
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=sf.net; s=x
 ;
 h=Content-Type:MIME-Version:References:In-Reply-To:Subject:Cc:To:From:
 Message-ID:Date:Sender:Reply-To:Content-Transfer-Encoding:Content-ID:
 Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc
 :Resent-Message-ID:List-Id:List-Help:List-Unsubscribe:List-Subscribe:
 List-Post:List-Owner:List-Archive;
 bh=zcVA2leKEHZCBy0L6O+DAKg05GvJhbtAx6yj2EYofvk=; b=cvrgtcF0PAQoSoI1HbtQvoUFBA
 NOZSqHExpZlGje6a4bq1zeJKPFfnY/iOeNBNbrsQE9bi5DpbHl1mb6qPK/LNfTUPgwJlIEaSks3O7
 P+HvDLipjQWvwlWkJkn/Um6ayyQO9Ym9DPboC6otsTp5GmQ87vRpNkDLfTtR/cRVwXS8=;
Received: from smtp-out1.suse.de ([195.135.220.28])
 by sfi-mx-2.v28.lw.sourceforge.com with esmtps
 (TLS1.2:ECDHE-RSA-AES128-GCM-SHA256:128) (Exim 4.94.2)
 id 1ncLDl-00087C-Ct
 for linux1394-devel@lists.sourceforge.net; Thu, 07 Apr 2022 06:02:18 +0000
Received: from relay2.suse.de (relay2.suse.de [149.44.160.134])
 by smtp-out1.suse.de (Postfix) with ESMTP id 29BA221117;
 Thu,  7 Apr 2022 06:02:11 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de; s=susede2_rsa;
 t=1649311331; h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
 mime-version:mime-version:content-type:content-type:
 in-reply-to:in-reply-to:references:references;
 bh=zcVA2leKEHZCBy0L6O+DAKg05GvJhbtAx6yj2EYofvk=;
 b=vZ2m/aITGXDAq6n8nhnsUrvPRMPIkKnWD/KRTTGFB0nr+ykHFGw/AEtWdF/ElB9rJTby5g
 zNbcBPB8Y50/7gHSfWJ/iEOpR6naCLf3Oe41SYm5L+Xa4ekwfdom+aUoi51z0/gBcsjLOt
 y8X0HtBS9VZ9cc/hc78ohGsHPsQxwd8=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
 s=susede2_ed25519; t=1649311331;
 h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
 mime-version:mime-version:content-type:content-type:
 in-reply-to:in-reply-to:references:references;
 bh=zcVA2leKEHZCBy0L6O+DAKg05GvJhbtAx6yj2EYofvk=;
 b=6z+z7H4qA0BPXVQG32Ue9gbbgIcmW0u3QrAwQSja86P/ki0wj6NwbYCk//jpel7RvfXrjt
 INS2E3TFJ5EGqoBg==
Received: from alsa1.suse.de (alsa1.suse.de [10.160.4.42])
 by relay2.suse.de (Postfix) with ESMTP id 1F97FA3B82;
 Thu,  7 Apr 2022 06:02:10 +0000 (UTC)
Date: Thu, 07 Apr 2022 08:02:10 +0200
Message-ID: <s5htub52zz1.wl-tiwai@suse.de>
From: Takashi Iwai <tiwai@suse.de>
To: Takashi Sakamoto <o-takashi@sakamocchi.jp>
Subject: Re: [PATCH v3 0/3] firewire: assist unit driver to compute packet
 time stamp
In-Reply-To: <Yk4r7VcotHz0iMOU@workstation>
References: <20220405072221.226217-1-o-takashi@sakamocchi.jp>
 <s5hczhv5wjc.wl-tiwai@suse.de> <Yk4r7VcotHz0iMOU@workstation>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
X-Spam-Score: -2.5 (--)
X-Spam-Report: Spam detection software,
 running on the system "util-spamd-2.v13.lw.sourceforge.com", 
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 the administrator of that system for details.
 Content preview:  On Thu, 07 Apr 2022 02:10:21 +0200, Takashi Sakamoto wrote:
 > > On Tue, Apr 05, 2022 at 06:23:35PM +0200, Takashi Iwai wrote: > > On
 Tue, 05 Apr 2022 09:22:18 +0200, > > Takashi Sakamoto wrote: > > > [...] 
 Content analysis details:   (-2.5 points, 6.0 required)
 pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -2.3 RCVD_IN_DNSWL_MED      RBL: Sender listed at https://www.dnswl.org/,
 medium trust [195.135.220.28 listed in list.dnswl.org]
 -0.0 SPF_PASS               SPF: sender matches SPF record
 0.0 SPF_HELO_NONE          SPF: HELO does not publish an SPF Record
 -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature
 -0.1 DKIM_VALID_EF          Message has a valid DKIM or DK signature from
 envelope-from domain
 -0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from
 author's domain
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
 valid -0.0 T_SCC_BODY_TEXT_LINE   No description available.
X-Headers-End: 1ncLDl-00087C-Ct
X-BeenThere: linux1394-devel@lists.sourceforge.net
X-Mailman-Version: 2.1.21
Precedence: list
List-Id: Linux IEEE 1394 development list
 <linux1394-devel.lists.sourceforge.net>
List-Unsubscribe: <https://lists.sourceforge.net/lists/options/linux1394-devel>, 
 <mailto:linux1394-devel-request@lists.sourceforge.net?subject=unsubscribe>
List-Archive: <http://sourceforge.net/mailarchive/forum.php?forum_name=linux1394-devel>
List-Post: <mailto:linux1394-devel@lists.sourceforge.net>
List-Help: <mailto:linux1394-devel-request@lists.sourceforge.net?subject=help>
List-Subscribe: <https://lists.sourceforge.net/lists/listinfo/linux1394-devel>, 
 <mailto:linux1394-devel-request@lists.sourceforge.net?subject=subscribe>
Cc: alsa-devel@alsa-project.org, linux1394-devel@lists.sourceforge.net,
 linux-kernel@vger.kernel.org
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Errors-To: linux1394-devel-bounces@lists.sourceforge.net

On Thu, 07 Apr 2022 02:10:21 +0200,
Takashi Sakamoto wrote:
> 
> On Tue, Apr 05, 2022 at 06:23:35PM +0200, Takashi Iwai wrote:
> > On Tue, 05 Apr 2022 09:22:18 +0200,
> > Takashi Sakamoto wrote:
> > > 
> > > Hi,
> > > 
> > > Current implementation of Linux FireWire subsystem doesn't allow unit
> > > driver to operate content of packet in IR context according to
> > > time stamp. Additionally it doesn't allow unit driver to read current value
> > > of CYCLE_TIME register in OHCI 1394 controller. It brings disadvantages to
> > > drivers in Linux sound subsystem in regards of handling time for sampled
> > > data such as PCM frames and MIDI messages.
> > > 
> > > This rerolled patchset is first step to improve the situation.
> > > 
> > > Changes in v3:
> > >  * Rebase v2 patchset to v5.18-rc1
> > > Changes in v2:
> > >  * Rebase v1 patchset to v5.16 release
> > >  * https://lore.kernel.org/lkml/20220212022131.199855-1-o-takashi@sakamocchi.jp/
> > > V1:
> > >  * https://lore.kernel.org/lkml/20211202113457.24011-1-o-takashi@sakamocchi.jp/
> > > 
> > > Hector Martin (1):
> > >   firewire: Add dummy read_csr/write_csr functions
> > > 
> > > Takashi Sakamoto (2):
> > >   firewire: add kernel API to access CYCLE_TIME register
> > >   firewire: add kernel API to access packet structure in request
> > >     structure for AR context
> > 
> > Thanks, applied all three patches now to for-next branch.
> 
> Although thanks for your applying them into your tree, I apologize to
> trouble you if you overlook that the included changes is just for Linux
> FireWire subsystem. It's my fault to send them only to Linux sound
> subsystem, but the changes are required to my work in sound drivers... 
> 
> If you are willing to include patches to Linux FireWire subsystem for
> your pull-request to Linus, I can prepare respined patches for it since
> I have the list of patches posted to LKML as bug fixes for Linux FireWire
> subsystem.
> 
> I need any help to solve current situation of Linux FireWire subsystem
> that bug fixes and new changes are hardly merged. Of course, IEEE 1394 bus
> is already outdated and legacy, but I know that some users still work
> with it. If your path is available for it, it's the easiest and the most
> convenient way for upstreaming, I think.

Ah OK, it's fine for me in either way.  I can keep up those changes in
my tree, or go through others.  I leave the decision Firewire
subsystem people.  Just let me know.


thanks,

Takashi


_______________________________________________
mailing list linux1394-devel@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/linux1394-devel
